'''yaml
# Utilize the latest version 2.1 of the CircleCI pipeline process engine to streamline your CI/CD workflows.
# Reference Documentation: https://circleci.com/docs/configuration-reference

version: 2.1

# Orbs are reusable packages of CircleCI configuration which allow you to share and encapsulate commands, jobs, and executors across multiple projects.
# For more on Orbs, visit: https://circleci.com/docs/orb-intro/

orbs:
  # Integrate the Node orb for managing Node.js applications with ease.
  # Check the Node orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.2

  # The S3 orb simplifies the process of setting up the AWS CLI and enables quick copying or syncing of files to Amazon S3.
  # Utilizing orbs minimizes configuration complexity for common tasks.
  # Learn more about the S3 orb here: https://circleci.com/developer/orbs/orb/circleci/aws-s3
  
  # IMPORTANT: Make sure to securely configure environment variables containing necessary secrets through the CircleCI UI.
  # For guidance, refer to: https://circleci.com/docs/set-environment-variable/#set-an-environment-variable-in-a-project
  aws-s3: circleci/aws-s3@4.0

# Define a job for executing tests
jobs:
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test

# Define a job for building and deploying the application
  build-and-deploy:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
    filters:
      branches:
        only: main
```      - run:
          command: npm run build
          name: Build application
      - aws-s3/sync:
          from: dist/
          to: s3://sample-app-vue
          arguments: --delete
      - run:
          command: |
            npm run deploy
          name: Deploy application

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - build-and-deploy:
          requires:
            - test
          filters:
            branches:
              only: main
